import "./globals.css";

// components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

import { Roboto } from "next/font/google";
import { Suspense } from "react";
import Loading from "./loading";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["100", "300", "400", "500", "700", "900"],
  style: ["normal", "italic"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Suspense fallback={<Loading />}>
          <div className="layout">
            <Header />
            <div className="page-content">{children}</div>
            <Footer />
          </div>
        </Suspense>
      </body>
    </html>
  );
}
